# --- Styling ---

# 1. Define the Active Pill (Inline colors override global styles)
setw -g window-status-current-format "#[fg=#89b4fa,bg=default]#[fg=#11111b,bg=#89b4fa,bold]#I:#W#[fg=#89b4fa,bg=default]"

# 2. Define the Inactive Pill
setw -g window-status-format "#[fg=#313244,bg=default]#[fg=#cdd6f4,bg=#313244]#I:#W#[fg=#313244,bg=default]"

# 3. Spacing and Alignment
setw -g window-status-separator " "
set -g status-justify left
set -g status-position top
#set -g status-style 'bg=default'
set -g status-style 'bg=#202020'

# 4. Status Content
set -g status-left-length 20
set -g status-left '#[fg=blue,bold]  #S #[fg=white]| '
set -g status-right-length 50
set -g status-right '#[fg=gray] %Y-%m-%d #[fg=white]| #[fg=blue,bold]%H:%M '

# --- Behavior ---

set -g mouse on
set -g prefix C-s

# Act like vim
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key -n S-Left previous-window
bind-key -n S-Right next-window

# Performance & Compatibility (Neovim suggestions)
set-option -sg escape-time 5
set-option -g focus-events on
set-option -a terminal-features 'foot:RGB'
